openapi: 3.0.0
info:
  title: Test OpenApi 3 spec
  description: Test that our plugins prefer to match responses to non-templated paths over templated paths
  version: 0.1.0
paths:
  /preferNonTemplatedPathOverTemplatedPath/nonTemplatedPath:
    get:
      responses:
        200:
          description: Response body should be a string
          content:
            application/json:
              schema:
                type: string
  /preferNonTemplatedPathOverTemplatedPath/{templatedPath}:
    get:
      responses:
        200:
          description: Response body should be a number
          content:
            application/json:
              schema:
                type: number
