swagger: '2.0'
info:
  description: Has one path
  title: Example OpenApi 2 spec with no basePath
  version: 0.1.0
paths:
  /endpointPath:
    get:
      responses:
        200:
          description: Response body should be a string
          schema:
            type: string
