openapi: 3.0.0
info:
  title: Example OpenApi 3 spec
  description: \'servers' is an empty array
  version: 0.1.0
servers: []
paths:
  /endpointPath:
    get:
      responses:
        200:
          description: Response body should be a string
          content:
            application/json:
              schema:
                type: string
