openapi: 3.0.0
info:
  title: Example OpenApi 3 spec
  description: Defines servers using server variables
  version: 0.1.0
servers:
  - url: /{variableInPath}
    description: server url with 1 server variable in the path
    variables:
      variableInPath:
        default: defaultValueOfVariableInPath
        enum:
          - enumValueOfVariableInPath
  - url: /{firstVariableInPath}/{secondVariableInPath}
    description: server url with multiple server variables in the path
    variables:
      firstVariableInPath:
        default: defaultValueOfFirstVariableInPath
      secondVariableInPath:
        default: defaultValueOfSecondVariableInPath
  - url: https://{hostVariable}.com:{portVariable}/
    description: server url with server variables only before the path
    variables:
      hostVariable:
        default: defaultValueOfHostVariable
      portVariable:
        default: '1234'
  - url: https://{hostVariable}.com:{portVariable}/{variableInDifferentPath}
    description: server url with server variables before and after the path
    variables:
      hostVariable:
        default: defaultValueOfHostVariable
      portVariable:
        default: '1234'
      variableInDifferentPath:
        default: defaultValueOfVariableInDifferentPath
paths:
  /endpointPath:
    get:
      responses:
        200:
          description: Response body should be a string
          content:
            application/json:
              schema:
                type: string
